# Generated by Django 3.2.9 on 2021-12-02 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_forgetpassword_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 2, 10, 39, 45, 623095)),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
