# Generated by Django 3.2.9 on 2021-12-03 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20211202_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('product_desc', models.CharField(max_length=30, null=True)),
                ('Product_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_status', models.BooleanField(default=False)),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 8, 8, 52, 24263)),
        ),
    ]
