# Generated by Django 3.2.9 on 2021-12-03 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_auto_20211203_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 11, 49, 11, 467648)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
