# Generated by Django 3.2.9 on 2021-12-03 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20211203_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_img',
            new_name='product_img',
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 12, 4, 27, 890121)),
        ),
    ]
