# Generated by Django 3.2.9 on 2021-12-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20211203_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 12, 28, 24, 81995)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
