# Generated by Django 3.2.9 on 2021-12-09 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_auto_20211203_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=40, null=True)),
                ('page_cat', models.CharField(max_length=30, null=True)),
                ('page_publish_date', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 9, 12, 27, 5, 288909)),
        ),
    ]
