# Generated by Django 3.2.6 on 2021-12-10 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_auto_20211210_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='teacher_name',
            new_name='parent_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='teacher_name',
            new_name='parent_name',
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 8, 9, 5, 266363)),
        ),
    ]
