# Generated by Django 3.2.9 on 2021-12-10 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_auto_20211210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Employee.parent'),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 11, 49, 36, 375440)),
        ),
    ]
