# Generated by Django 3.2.9 on 2022-01-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_alter_forgetpassword_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 20, 13, 41, 8, 386529)),
        ),
    ]
